### ISSUE TITLE
import rmarkdown fails to create notebook

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.flexdashboard#10]
Advanced/Import from Rmarkdown fails with the following error:

```
Error: importRmd: Error in fun(...) : failed to create new notebook
R trace:
stop("failed to create new notebook")
fun(...)
at success (http://127.0.0.1:8080/js/rcloud_bundle.js:142:23)
From previous event:
at Object.importRmd (http://127.0.0.1:8080/js/rcloud_bundle.js:148:54)
at HTMLSpanElement.do_import (rcloud.rmd.js:55:40)
at HTMLSpanElement.dispatch (http://127.0.0.1:8080/lib/js/jquery-2.1.1.js:4409:9)
at HTMLSpanElement.elemData.handle (http://127.0.0.1:8080/lib/js/jquery-2.1.1.js:4095:28)
```

**Comment by gordonwoodhull** [comment]
@gaborcsardi, you're off the hook - just logging this because this is the first time I tested this side of things, and it's been a long day.

**Comment by gaborcsardi** [comment]
@gordonwoodhull do you have an example notebook?

**Comment by gaborcsardi** [comment]
Btw. the import/export is in the `rcloud.rmd` package I think.

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.rmd#16
